stefanberger/libtpms

.travis.yml

Add Travis build script.
Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>

ci: add .travis.yml

---

configure.ac
include/libtpms/tpm_types.h
src/Makefile.am
src/tpm2/ExecCommand.c
src/tpm2/Implementation.h
src/tpm2/LibtpmsCallbacks.c
src/tpm2/LibtpmsCallbacks.h
src/tpm2/NVMarshal.c
src/tpm2/NVMem.c
src/tpm2/PPPlat.c
src/tpm2/PropertyCap.c
src/tpm2/StateMarshal.c
src/tpm2/TpmFail.c
src/tpm2/Volatile.c
src/tpm2/Volatile.h
src/tpm_library.c
src/tpm_tpm12_interface.c
src/tpm_tpm2_interface.c
src/tpm_tpm2_tis.c

These patches make libtpms compile on older systems.

Make libtpms compile on older systems

---

src/tpm2/NVMarshal.c

This series of patches addresses 2 coverity issues.
Stefan

Address 2 coverity issues

---

src/tpm2/Implementation.h

tpm2: Disable CC_Vendor_TCG_Test

---

README
configure.ac
src/Makefile.am
tests/Makefile.am
tests/fuzz-main.c
tests/fuzz.cc
tests/fuzz.sh
tests/oss-fuzz.sh

see second commit for details.

Fuzz: better oss-fuzz integration

---

.gitignore
.travis.yml
tests/Makefile.am
tests/base64decode.sh
tests/fuzz.sh
tests/tpm2_createprimary.c
tests/tpm2_pcr_read.c
tests/tpm2_selftest.c
tests/tpm2_selftest.sh

Fix some issues with test cases and have Travis display the last 50 lines of test logs in case an error happens.

Fix some issues with test cases and have Travis display test logs in case of error

---

.travis.yml
src/tpm2/NVCommands.c
src/tpm2/NVMem.c

This series of patches fixes some issues related to building for Coverity and fixes issues detected by Coverity.

Coverity fixes

---

src/tpm2/BnConvert.c
src/tpm2/ExecCommand.c
src/tpm2/PropertyCap.c
src/tpm2/TpmFail.c
src/tpm2/TpmSizeChecks.c
src/tpm2/crypto/openssl/CryptCmac.c

Add some missing 'libtpms added' comments.

Libtpms added

---

configure.ac
src/tpm2/crypto/openssl/CryptRsa.c
src/tpm2/crypto/openssl/Helpers.c
src/tpm2/crypto/openssl/Helpers_fp.h

tpm2: Implement key creation with OpenSSL for rand == NULL

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

Prepare for 0.7.0 release

---

debian/control

Address a few issues in the control file as reported by lintian.

debian: Address linitian issues in control file

---

.travis.yml
src/tpm12/tpm_counter.c
src/tpm12/tpm_key.c
src/tpm12/tpm_process.c

This series fixes yet some more compiler errors (false positives) occurring with -O3

Fix yet some more compiler errors (false positives) occurring with -O3

---

src/tpm12/tpm_delegate.c
src/tpm12/tpm_nvram.c
src/tpm12/tpm_process.c
src/tpm12/tpm_session.c
src/tpm12/tpm_transport.c

Backport some TPM 1.2 patches due to gcc 10.

gcc 10 fixes

---

src/tpm2/crypto/openssl/CryptRsa.c

For the RSA decryption we have to use an output buffer of the size of the
(largest possible) RSA key for the decryption to always work.
This fixes a stack corruption bug that caused a SIGBUS and termination of
'swtpm'.

tpm2: Fix output buffer parameter and size for RSA decyrption

---

configure.ac
dist/libtpms.spec
include/libtpms/tpm_library.h

build-sys: Build libtpms 0.7.2

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in
src/tpm2/crypto/openssl/CryptRsa.c

This PR prepares for the 0.7.2 release.

Prepare for 0.7.2 release

---

CHANGES

CHANGES: Update CHANGES file for 0.8.0

---

debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

rpm/debian: Add 0.8.0-1 entry to changelog

---

configure.ac

build-sys: Enable automake silent rules

---

src/tpm2/CommandDispatchData.h
src/tpm2/Global.h
src/tpm2/Marshal.c
src/tpm2/Marshal_fp.h
src/tpm2/OIDs.h
src/tpm2/PCR.c
src/tpm2/TpmBuildSwitches.h
src/tpm2/TpmSizeChecks.c
src/tpm2/Unmarshal.c
src/tpm2/Vendor_TCG_Test_fp.h
src/tpm2/crypto/CryptSym.h
src/tpm2/crypto/openssl/LibSupport.h
src/tpm2/crypto/openssl/TpmToOsslHash.h
src/tpm2/crypto/openssl/TpmToOsslSym.h
tests/tpm2_pcr_read.c

This PR contains more updates for revision 162.

More updates for rev162

---

.travis.yml

Travis: Add python3 dependencies for swtpm test

---

src/Makefile.am
src/tpm2/BnMath.c
src/tpm2/crypto/CryptEccMain_fp.h
src/tpm2/crypto/openssl/BnMath_fp.h
src/tpm2/crypto/openssl/ConsttimeUtils.h
src/tpm2/crypto/openssl/CryptEccMain.c
src/tpm2/crypto/openssl/CryptEccSignature.c
src/tpm2/crypto/openssl/Helpers.c
src/tpm2/crypto/openssl/Helpers_fp.h
src/tpm2/crypto/openssl/consttime.txt

This PR addresses potential constant time issues in the TPM 2 ECC code.

Address a potential constant time issues in the TPM 2 ECC code

---

src/Makefile.am
src/tpm2/BnMath.c
src/tpm2/crypto/CryptEccMain_fp.h
src/tpm2/crypto/openssl/BnMath_fp.h
src/tpm2/crypto/openssl/ConsttimeUtils.h
src/tpm2/crypto/openssl/CryptEccMain.c
src/tpm2/crypto/openssl/CryptEccSignature.c
src/tpm2/crypto/openssl/Helpers.c
src/tpm2/crypto/openssl/Helpers_fp.h
src/tpm2/crypto/openssl/consttime.txt

This PR addresses potential constant time issues in the TPM 2 ECC code.

Address potential constant time issues in the TPM 2 ECC code

---

CHANGES
configure.ac
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in
include/libtpms/tpm_library.h

This PR prepares for 0.7.4 release

Prepare for 0.7.4 release

---

debian/changelog

debian: Add missing line in changelog

---

src/tpm2/NVMarshal.c
src/tpm2/Policy_spt.c

This PR fixes some issued detected by UBSAN.

Fix some issues detected by UBSAN

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in
src/tpm2/crypto/openssl/CryptPrime.c

This PR prepares for the 0.7.5 release.

Prepare for 0.7.5 release

---

CHANGES
src/tpm2/BackwardsCompatibilityObject.c
src/tpm2/CompilerDependencies.h

This PR makes some last changes for 0.8 and updates the CHANGES document for 0.8.0.

Last changes for 0.8. and update CHANGES document

---

src/tpm2/NVMarshal.c
src/tpm2/crypto/openssl/CryptCmac.c
src/tpm2/crypto/openssl/CryptRand.c
src/tpm2/crypto/openssl/CryptSym.c

This PR backports a few patches that address mostly false positives reported by Coverity.

Backport a few patches to address mostly false positives reported by Coverity

---

src/tpm2/crypto/openssl/Helpers.c

For some peace-of-mind add a function that allows us to check the RSA keys
that are generated, especially the primary keys that are not generated by
OpenSSL.
Use the following configure line to compile libtpms:
```
CFLAGS="-DDO_RSA_CHECK_KEY=1" ./autogen.sh --prefix=/usr \
--with-tpm2 --with-openssl
```
Start swtpm after installing libtpms:
```
swtpm socket --tpmstate dir=/tmp/myvtpm --tpm2 --ctrl type=tcp,port=2322  \
--server type=tcp,port=2321 --flags not-need-init --log level=0
```
We can now run this test program to check keys by using an RSA primary key
for signing.
```
export TPM_COMMAND_PORT=2321 TPM_PLATFORM_PORT=2322 \
TPM_SERVER_NAME=localhost TPM_INTERFACE_TYPE=socsim \
TPM_SERVER_TYPE=raw
echo "test" > input
swtpm_ioctl --tcp :${TPM_PLATFORM_PORT} -i
tssstartup
while :; do …
```

tpm2: Test RSA private keys when -DDO_CHECK_RSA_KEY=1 is used

---

debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

rpm/debian: Adjust date of 0.8.0 entry in changelog

---

src/tpm2/NVMarshal.c

This patch addresses the bug reported in issue #195 where the saving of
an externally loaded public key's context doesn't work due to the usage of
ANY_CONTEXT_SAVE for saving key contexts. This patch fixes the issue by
creating local versions of TPM_SENSITIVE_Marshal/_Unmarshal that deals
with the case where sensitiveType is not a type of private key but a
public key instead that basically doesn't have much information in
TPM_SENSITIVE but is all zeros instead.

tpm2: Fix public key context save due to ANY_OBJECT_Marshal usage

---

configure.ac
dist/libtpms.spec
include/libtpms/tpm_library.h

build-sys: Build libtpms v0.8.4

---

man/man3/TPMLIB_RegisterCallbacks.pod
src/tpm2/Marshal.c

This PR fixes
- a #if ALG_CAMELLIA in the TPM 2 code
- the code example in TPMLIB_RegisterCallbacks manpage

Some fixes

---

tests/fuzz.cc

We have to store the permall state blob once it has been initialized since
otherwise some fields are not having proper values in the internal state.

tests: fuzz: Store initialized permall state blob

---

src/tpm2/NVMarshal.c
src/tpm2/Object.c

This PR fixes two issues related to marshalling of the state of the TPM 2.

Fix a couple of issues related to marshalling of state

---

src/tpm2/NVMarshal.c
src/tpm2/Object.c

This PR backports a few critical patches from the master branch

Backport a few critical patches

---

configure.ac
dist/libtpms.spec
include/libtpms/tpm_library.h
src/tpm2/NVMarshal.c
src/tpm2/Object.c

This PR backports a few critical patches from the master branch

Backport a few critical patches 

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

Prepare for 0.8.5 release

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

Prepare for 0.7.9 release

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

Prepare for 0.6.6 release

---

src/tpm2/gensymtestsdata.sh

Extend the test case data generation script for sm4. Since several
distros' openssl do not support sm4, we need to test for whether sm4
is supported by the installed openssl.

tpm2: Extend asym key test case data generation script for sm4

---

CHANGES
src/tpm2/NVMarshal.c
src/tpm2/TpmProfile.h
src/tpm_tpm2_interface.c

Enable Camellia symmetric encryption

Enable Camellia symmetric encryption

---

CHANGES
configure.ac
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in
include/libtpms/tpm_library.h
src/tpm2/NVMarshal.c

Prepare for 0.8.6 release with a bugfix related to TPM 2 event sequence marshalling

Prepare for 0.8.6 release with a bugfix related to TPM 2 event sequence marshalling

---

configure.ac
dist/libtpms.spec
include/libtpms/tpm_library.h
src/tpm2/crypto/openssl/CryptRsa.c
src/tpm2/crypto/openssl/Helpers.c

This PR backports some OpenSSL 3.0 patches for the upcoming v0.8.7

Backport some OpenSSL 3.0 patches to upcoming v0.8.7

---

debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

This PR prepares for release of v0.8.7.

Prepare for release of v0.8.7

---

CHANGES
configure.ac
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in
include/libtpms/tpm_library.h
src/tpm2/NVMarshal.c
src/tpm2/crypto/openssl/CryptRsa.c
src/tpm2/crypto/openssl/Helpers.c

Prepare for release of v0.7.10

Prepare for release of v0.7.10

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

Prepare for release of libtpms v0.9.0

Prepare for release of v0.9.0

---

debian/changelog

debian: Adjust changelog for 0.10.0~dev1

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

Prepare for release of v0.9.1

---

debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

rpm/debian: Add 0.9.2 entry in changelog

Prepare for v0.9.2 release

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

This PR prepares for release of v0.9.3

Prepare for v0.9.3 release

---

src/tpm12/tpm_nvram.c
src/tpm2/Marshal.c

Backport some patches that gcc for s390x on Ubuntu Impish needs.

Backport some patches for gcc on s390x Ubuntu Impish 

---

src/tpm12/tpm_cryptoh.c
src/tpm12/tpm_delegate.c
src/tpm12/tpm_migration.c
src/tpm12/tpm_session.c
src/tpm12/tpm_session.h

This PR resolves some issue discovered by Coverity in agressive mode.

Resolve some issue discovered by Coverity in agressive mode

---

src/tpm2/BnMath.c

tpm2: Fix a potential overflow expression (coverity)

---

src/tpm2/crypto/openssl/Helpers.c

This PR builds on part 1.
Implement OpenSSLCryptRsaGenerateKey for OpenSSL 3.0 case

Implement some more of the functions in Helpers.c with OpenSSL 3.0 APIs (part 2)

---

MAINTAINERS

Add MAINTAINERS file to project

---

CHANGES
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in

Prepare for v0.7.11 release

---

src/tpm2/crypto/openssl/Helpers.c

Replace usage of deprecated DES_random_key() with EVP_CIPHER API calls. These newer calls are much more time consuming than the deprecated call.

tpm2: Replace usage of deprecated DES_random_key() (OSSL 3)

---

src/tpm2/CryptUtil.c
src/tpm2/EACommands.c
src/tpm2/ExecCommand.c
src/tpm2/SessionProcess.c
src/tpm2/SessionProcess_fp.h
src/tpm2/crypto/CryptUtil_fp.h
src/tpm2/crypto/openssl/CryptDes.c

Synchronize with upstream to fix some recently discovered issues described in TPM 2 errata v1.4.

Fix some issues by synchronizing with upstream

---

src/Makefile.am
src/tpm2/AsymmetricCommands.c
src/tpm2/AttestationCommands.c
src/tpm2/AuditCommands.c
src/tpm2/CommandDispatchData.h
src/tpm2/ContextCommands.c
src/tpm2/Entropy.c
src/tpm2/MathOnByteBuffers.c
src/tpm2/PlatformData.h
src/tpm2/StartupCommands.c
src/tpm2/SymmetricCommands.c
src/tpm2/crypto/ECC_Decrypt_fp.h
src/tpm2/crypto/ECC_Encrypt_fp.h
src/tpm2/crypto/openssl/BnValues.h
src/tpm2/crypto/openssl/CryptEccCrypt.c
src/tpm2/crypto/openssl/LibSupport.h

This PR syns with the upstream repo

Sync with upstream repo

---

src/tpm2/SymmetricTest.h
src/tpm2/crypto/CryptSym.h
src/tpm2/crypto/openssl/CryptEccSignature.c
src/tpm2/crypto/openssl/Helpers.c

Ran into compile errors when disabling/enabling certain algorithms.
Signed-off-by: Ben Lytle <ben.dav.lytle@hpe.com>

Add missing algorithm macro checks

---

CHANGES
configure.ac
debian/changelog
dist/libtpms.spec
dist/libtpms.spec.in
include/libtpms/tpm_library.h
src/tpm2/CryptUtil.c
src/tpm2/EACommands.c
src/tpm2/ExecCommand.c
src/tpm2/Object.c
src/tpm2/SessionProcess.c
src/tpm2/SessionProcess_fp.h
src/tpm2/crypto/CryptUtil_fp.h
src/tpm2/crypto/openssl/CryptDes.c

This PR backports a few patches to libtpms v0.9.7.

Backport a few patches for libtpms v0.9.7

---

src/tpm2/crypto/openssl/Helpers.c

Like OpenSSL use the Carmichael function for the RSA private exponent D when an RSA key has >= 2048 bits rather than the Euler totient function.
The main difference is that by TPM 2 using the Carmichael function OpenSSL now behaves the same way as when it is used by other programs that for example load keys from PEM files where the private exponent D was calculated with this function. The difference is seen when for example blobs cannot be decrypted where newer versions of OpenSSL (with implicit rejection enabled) returned results of 48 bytes every time rather than a deterministic (for same input blob) but varying number of bytes (Euler totient).
Switching to the Carmichael function does not have any negative impact on interoperatibility with OpenSSL nor does it affect interoperability …

tpm2: Use Carmichael function for RSA priv. exponent D (>= 2048 bits)

---

src/tpm2/NVMarshal.c
src/tpm2/RuntimeCommands.c

- Fix an out-of-bounds access in a debug statement.
- Display an error message if a (checked) value is larger than expected.

Fix 2 issues

---

man/man3/TPMLIB_SetProfile.pod
src/Makefile.am
src/tpm2/CapabilityCommands.c
src/tpm2/CommandAttributeData.h
src/tpm2/CommandDispatchData.h
src/tpm2/EACommands.c
src/tpm2/Entity.c
src/tpm2/Global.h
src/tpm2/Marshal.c
src/tpm2/Marshal_fp.h
src/tpm2/NVCommands.c
src/tpm2/NVMarshal.c
src/tpm2/NV_DefineSpace2_fp.h
src/tpm2/NV_ReadPublic2_fp.h
src/tpm2/NV_spt.c
src/tpm2/PolicyParameters_fp.h
src/tpm2/RuntimeCommands.c
src/tpm2/RuntimeProfile.c
src/tpm2/Session.c
src/tpm2/SessionProcess.c
src/tpm2/SetCapability_fp.h
src/tpm2/TpmAlgorithmDefines.h
src/tpm2/TpmProfile_CommandList.h
src/tpm2/TpmProfile_Common.h
src/tpm2/TpmTypes.h
src/tpm2/Unmarshal.c
src/tpm2/Unmarshal_fp.h
tests/nvram_offsets.c
tests/tpm2_setprofile.c

This PR adds the new commands that were added and enables PolicyCapability and PolicyParameters commands in the default-v1 profile. They will only be enabled once profiles support has been added.

rev180 part2: Add new commands and enable a few of them.

---

src/tpm2/RuntimeProfile.c

Deduplicate verbs in Commands, Algorithms, and Attributes strings in a profile and when a verb with an '=' sign is found, such as ecc-min-size=224, and there is a duplicate later in the string, such as ecc-min-size=256, then keep the last one.

tpm2: Deduplicate verbs in Commands, Algorithms, and Attributes strings in profile

---

src/tpm2/CryptUtil.c

Add a missing break statement that was forgotten in recent commit b389781f49e43.

tpm2: Add missing break statement

---

src/tpm2/RuntimeProfile.c

Allow the name of custom profiles to also have the prefix 'custom:'.

tpm2: Allow naming of custom profiles with prefix 'custom:'
