- src/Makefile.am
libtpms.syms is inside the source directory, so when doing out
of tree builds it can't be found - fix the libtool invocation.
> build: fix out of tree builds

- configure.ac
- src/tpm2/NVMarshal.c
- src/tpm2/NVMarshal.h
- src/tpm2/StateMarshal.c
- src/tpm2/StateMarshal.h
- src/tpm2/Test.h
- src/tpm2/Volatile.c
- src/tpm2/Volatile.h
The two patches in this series fix some license headers in files 'I' wrote and fix the build for RHEL 6.
> Fix license headers and build on RHEL 6

- src/tpm2/Global.h
- src/tpm2/NVMarshal.c
STATE_RESET_DATA and STATE_CLEAR_DATA need to only be written if the
orderlyState has TPM_SU_STATE (after masking out some other bits) set.
We bump up the version of the PERSISTENT_STATE to 3 and since previous
versions cannot deal with the missing STATE_{RESET,CLEAR}_DATA we require
that the minimum supported version understood by the implementation is
also '3'. This prevents downgrading of libtpms to a version prior to this
(patch).
> tpm2: Only write STATE_RESET and STATE_CLEAR blobs when needed

- README
- src/tpm_library.c
- src/tpm_library_intern.h
- src/tpm_tpm2_interface.c
- tests/run-fuzzer.sh
Log the TPM 2 command that put it into failure mode.
When entering failure mode _rpc__Send_Command() returns a different buffer with the response message than the buffer that was passed into it. So we need to check for this and copy from the returned buffer into the expected one.
Wrap the running of the fuzzer into a script so we can run each instance of the fuzzer in a temporary directory where it creates its own private NvChip file.
> Fix some issues related to TPM 2 failure mode and running the fuzzer

- .travis.yml
- configure.ac
- src/Makefile.am
- tests/Makefile.am
Add coverage support to the build system and fix the CFLAGS passing from the command line.
Add a Travis build that gets swtpm from the git repo and builds it and runs the test suite with code coverage enabled for libtpms.
Unfortunately cpp-coveralls cannot properly process all the input file due to malforming the path of the source files, so the results are currently not good unless I can figure out how to invoke cpp-coveralls or cpp-coveralls gets fixed.
> Add support for code coverage and a travis build that checks libtpms using swtpm

- man/man3/Makefile.am
Some man pages were not installed due to a typo in the name of
the variable. This patch fixes the issue.
> build-sys: Fix typo in manpages variable name

- src/tpm2/crypto/openssl/TpmToOsslMath.c
Some OpenSSL EC API calls are deprecated in OpenSSL >= 1.1.1
and may fail the build due to the #warning.
The affected functions have been renamed and consolidated with
other functions:
- EC_POINT_set_affine_coorindates_GFp
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/ec/ec_lib.c#L730
- EC_POINT_get_affine_coordinates_GFp
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/ec/ec_lib.c#L768
On both functions the suffix _GFp has been removed by the renaming.
We need to call the new functions if OPENSSL_API_COMPAT is defined
and is >= 0x10200000L.
> tpm2: Adapt code for OpenSSL 1.2 deprecated API calls

- .travis.yml
- src/tpm2/crypto/openssl/TpmToOsslMath.c
Backport some cherry-picked patches from master:
- travis: add libseccomp-dev as a package to install for swtpm
- fix openssl 1.2 deprecated API calls
> Backport some cherry-picked patches

- src/Makefile.am
- tests/oss-fuzz.sh
This script will permit integration with Google OSS-FUZZ
https://github.com/google/oss-fuzz
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
> build-sys: add oss-fuzz support

- .travis.yml
Add the option -b ./src for proper path creation. Exclude the test
dir to avoid malformed path creation. Also exclude the swtpm dir
since nothing interesting is to be found there.
> travis: Use cpp-coveralls with the -b option for proper path creation

- src/Makefile.am
- src/tpm12/tpm_auth.c
- src/tpm12/tpm_auth.h
- src/tpm12/tpm_crypto.c
- src/tpm12/tpm_crypto.h
- src/tpm12/tpm_cryptoh.c
- src/tpm12/tpm_cryptoh.h
- src/tpm12/tpm_digest.c
- src/tpm12/tpm_digest.h
- src/tpm12/tpm_global.c
- src/tpm12/tpm_global.h
- src/tpm12/tpm_identity.c
- src/tpm12/tpm_identity.h
- src/tpm12/tpm_key.c
- src/tpm12/tpm_key.h
- src/tpm12/tpm_load.c
- src/tpm12/tpm_load.h
- src/tpm12/tpm_maint.c
- src/tpm12/tpm_owner.c
- src/tpm12/tpm_pcr.c
- src/tpm12/tpm_pcr.h
- src/tpm12/tpm_process.c
- src/tpm12/tpm_startup.c
- src/tpm12/tpm_startup.h
- src/tpm12/tpm_storage.c
- src/tpm12/tpm_storage.h
- src/tpm12/tpm_store.c
- src/tpm12/tpm_store.h
- src/tpm12/tpm_ver.c
- src/tpm12/tpm_ver.h
There are quite a few unused functions in the TPM 1.2 code and this patch comments them out.
Also the TPM 1.2 maintenance commands are not useful. Deactivate them as well, which also increases code coverage using swtpm's TPM 1.2 test suite.
> tpm12: Deactivate unused code and maintenance commands

- src/tpm2/Marshal_fp.h
... and TPMU_PUBLIC_PARMS_Marshal is used, so leave its prototype active.
> tpm2: TPMT_PUBLIC_PARMS_Marshal is unused

- .travis.yml
Change file and directory ownerships so that we can run cpp-coveralls
without sudo.
> travis: Run cpp-coveralls without sudo

- src/Makefile.am
Remove some cruft that was useful when TPM 2 code was still in the
works but now that things have settled don't need it anymore.
> build-sys: Remove cruft from 'check'

- src/tpm2/Manufacture.c
- src/tpm2/NVMem.c
Add some missing #define TPM_HAVE_TPM2_DECLARATIONS before the include
of "tpm_library_intern.h" in TPM 2 code so we don't run into compile
errors on RHEL 6 when data types are redefined in TPM 1.2 code.
Previous patch 73cad883bac seems to have missed those.
> Add missing #define TPM_HAVE_TPM2_DECLARATIONS in tpm2 code (RHEL 6)

- tests/run-fuzzer.sh
- tests/tpm2_createprimary.sh
- tests/tpm2_pcr_read.sh
libtool already provides helper scripts around executables.
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
> build-sys: don't tweak LD_LIBRARY_PATH

- src/Makefile.am
- src/tpm2/Global.h
- src/tpm2/Utils.h
Move NV_ROUNDUP to Utils.h and call it TPM2_ROUNDUP for reuse by
other functions.
> tpm2: Rename NV_ROUNDUP to TPM2_ROUNDUP and move to new Utils.h

- src/tpm2/crypto/openssl/TpmToOsslMath.c
> tpm2: Clear all EC_POINT and BIGNUM before freeing

- .travis.yml
- src/Makefile.am
- src/tpm2/Implementation.h
- src/tpm2/Utils.h
- src/tpm2/crypto/openssl/CryptSym.c
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm2/crypto/openssl/Helpers_fp.h
- src/tpm2/crypto/openssl/TpmToOsslDesSupport.c
This set of patches adds an implementation for using OpenSSL's symmetric cipher functions (EVP) for AES and TDES. We leave the original code around, which again can be activate by setting USE_OPENSSL_FUNCTIONS to 'NO'.
> Have the TPM 2 code use OpenSSL's symmetric cipher functions for AES and TDES.

- .travis.yml
- configure.ac
- src/tpm2/Implementation.h
- src/tpm2/crypto/openssl/CryptSym.c
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm2/crypto/openssl/TpmToOsslDesSupport.c
OpenSSL's crypto library does not support all crypto functionality
we need in all versions. Elliptic curve support via EVP seems to
have been added much later than for example symmetric crypot support.
So, we move the USE_OPENSSL_FUNCTIONS out of Implementation.h
into configure.ac and let the build system detect what functionality
is available in the crypto library. In this patch we now rename
USE_OPENSSL_FUNCTIONS to USE_OPENSSL_FUNCTIONS_SYMMETRIC to indicate
that we can use the symmetric crypto functions of the crypto lib.
> build-sys: Add support for --enable-use-openssl-functions

- configure.ac
- src/tpm2/crypto/openssl/CryptEccSignature.c
- src/tpm2/crypto/openssl/TpmToOsslMath.c
- src/tpm2/crypto/openssl/TpmToOsslMath_fp.h
Switch the ECDSA signature verification to OpenSSL. Do the signature
creation in the next step so we can verify the creation / verification
against the original TPM 2 code.
> Switch ECDSA signature verification to OpenSSL

- configure.ac
- src/tpm2/crypto/openssl/CryptEccSignature.c
- src/tpm2/crypto/openssl/TpmToOsslMath.c
- src/tpm2/crypto/openssl/TpmToOsslMath.h
- src/tpm2/crypto/openssl/TpmToOsslMath_fp.h
This series of patches converts the ECDSA signing code to use OpenSSL crypto library functions.
> Use OpenSSL function for ECDSA signature creation

- configure.ac
- src/tpm2/crypto/openssl/CryptDes.c
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm2/crypto/openssl/Helpers_fp.h
Use OpenSSL function to create TDES keys if rand == NULL,
which indicates that a truely random key needs to be generated
rather than one derived from a KDF.
> tpm2: Use OpenSSL to create TDES keys if rand == NULL

- configure.ac
- src/tpm2/crypto/openssl/CryptRsa.c
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm2/crypto/openssl/Helpers_fp.h
This series of patches converts existing RSA code for encryption and signing to use OpenSSL code for doing these operations.
> Convert to OpenSSL RSA functions for encrypting and signing

- src/tpm2/crypto/openssl/CryptRsa.c
Use OpenSSL funtions now also for decryption and signature verification.
> tpm2: Use OpenSSL for decryption and signature verification

- m4/ax_check_define.m4
autoconf 2.63 is sufficient as a dependency for AX_CHECK_DEFINE
> build-sys: Require only autoconf 2.63 for older systems

- src/tpm2/CryptUtil.c
Fix a Coverity complaint by using iv.t.buffer rather than the
1-byte synonym (due to union) iv.b.buffer.
> tpm2: Fix Coverity complaint by using iv.t.buffer

- debian/control
- dist/libtpms.spec
- dist/libtpms.spec.in
Build now requires g++ compiler for fuzz tests. Add it to the build dependencies.
> Add missing packages to spec files for RPM and Debian

- src/tpm2/Volatile.c
Check the size of the available data before hashing them. A minimum
of 20 bytes needs to be passed into the function so that we can hash
the data 'before' it.
Reported-by: Yi Ren <yunye.ry@alibaba-inc.com>
> tpm2: Check data size to be at least size of hash

- src/tpm12/tpm_nvfile.c
Fix a potential buffer overflow bug in the creation of filenames
that were using sprintf() rather than snprintf(). The buffer overflow
could occurr if the buffer is longer than 4096 bytes. The state path
may alone be 4096 bytes and could possibly trigger the overflow.
Swtpm for example is not affected from this since it uses the callbacks
that are invoked before the faulty function is called.
> tpm12: Fix potential buffer overflow in filename creation

- configure.ac
Avoid the accumulation of -lcrypto while testing for symbols in the -lcrypto
library by saving the LIBS variable before doing the series of tests.
> build-sys: Avoid accumulation of -lcrypto

- README
We were missing CXX=clang++ in the docs for the fuzzer build. Add it.
> docs: Update READLE to include CXX=clang++ for fuzzer build

- src/tpm2/AlgorithmTests.c
- src/tpm2/crypto/openssl/Helpers.c
This series of patches adds a missing break statement to the TDES function selector part and makes sure that all symmetric crypto modes are always tested.
> Add a missing break statement and always test symmetric modes

- src/tpm2/Implementation.h
We define USE_SPEC_COMPLIANT_PROOFS which overrides PRIMARY_SEED_SIZE in
Implentation.h and cause PRIMARY_SEED_SIZE to be set to 64. Nevertheless,
adjust the value in Implementation.h.
> tpm2: Clarify that PRIMARY_SEED_SIZE is 64 per USE_SPEC_COMPLIANT_PROOFS

- src/tpm12/tpm_nvfile.c
Replace the strcpy with the safer strncpy version.
> tpm12: Replace strcpy with safer strncpy

- src/tpm2/SessionProcess.c
This patch fixes a bug described in the following TCG Document
ERRATA; Errata Version 1.9, August 23, 2019; For TCG Trusted Platform
Module Library; Family "2.0", Level 00, Revision 1.38, Sept 29, 2016
section 2.34: NV PIN Indices
> tpm2: Fix a bug in CheckAuthSession

- src/tpm2/Marshal.c
- src/tpm2/Unmarshal.c
Some TDES related marshalling and unmarshalling functions were
missing, so add them. Now TDES keys can be created.
Signed-off-by: stefan Berger <stefanb@linux.ibm.com>
> tpm2: Add missing TDES un-/marshalling functions

- src/tpm2/AlgorithmTests.c
- src/tpm2/HashTestData.h
The SMAC test now covers CMAC as well but covers more code paths.
> tpm2: Convert CMAC test to SMAC test for better coverage

- src/tpm2/Marshal.c
- src/tpm2/Unmarshal.c
This is a backport of 2da6f27c33.
Some TDES related marshalling and unmarshalling functions were
missing, so add them. Now TDES keys can be created.
Signed-off-by: stefan Berger <stefanb@linux.ibm.com>
> tpm2: Fix TDES key creation by adding missing un-/marshalling functions

- src/tpm12/tpm_nvfile.c
Use length + 1 as size parameter to strncpy() to address a Coverity
issue (false positive).
> tpm12: coverity: Use length + 1 for strncpy() parameter

- src/tpm12/tpm_nvfile.c
Revert the changes trying to use strncpy to now use strcpy again.
Recent compilers complain like this:
tpm12/tpm_nvfile.c: In function ‘TPM_NVRAM_Init’:
tpm12/tpm_nvfile.c:138:9: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
138 |         strncpy(state_directory, tpm_state_path, length + 1);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tpm12/tpm_nvfile.c:130:18: note: length computed here
130 |         length = strlen(tpm_state_path);
|                  ^~~~~~~~~~~~~~~~~~~~~~
tpm12/tpm_nvfile.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-self-assign’ [-Werror]
cc1: all warnings being treated as errors
> tpm12: Revert changes using strncpy to now use strcpy again

- src/tpm2/ObjectCommands.c
This patch addresses the following valgrind issue detetcted by swtpm test suite:
== Syscall param write(buf) points to uninitialised byte(s)
==3515669==    at 0x4DC14B7: write (in /usr/lib64/libc-2.30.so)
==3515669==    by 0x48547FB: write_full (utils.c:242)
==3515669==    by 0x48548F3: writev_full (utils.c:301)
==3515669==    by 0x48520A6: SWTPM_IO_Write (swtpm_io.c:229)
==3515669==    by 0x4850662: mainLoop (mainloop.c:282)
==3515669==    by 0x402BE7: swtpm_main (swtpm.c:497)
==3515669==    by 0x4CF61A2: (below main) (in /usr/lib64/libc-2.30.so)
==3515669==  Address 0x52413a2 is 34 bytes inside a block of size 2,006 alloc'd
==3515669==    at 0x483980B: malloc (vg_replace_malloc.c:309)
==3515669==    by 0x48548A1: writev_full (utils.c:287)
==3515669==    by 0x48520A6: SWTPM_IO_Write …
> tpm2: Initialize variable to address valgrind complaint

- src/tpm12/tpm_delegate.c
- src/tpm12/tpm_session.c
gcc (Ubuntu 9.2.1-21ubuntu1) 9.2.1 20191130
The gcc compiler on Ubuntu Focal reports several false positives for
potentially uninitialized variables:
tpm12/tpm_session.c: In function ‘TPM_Process_SaveContext’:
tpm12/tpm_session.c:3229:19: error: ‘tpm_auth_session_data’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
3229 |      returnCode = TPM_AuthSessionData_Store(&r1ContextSensitive, tpm_auth_session_data);
|                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tpm12/tpm_delegate.c: In function ‘TPM_Process_DelegateManage’:
tpm12/tpm_delegate.c:1787:49: error: ‘familyRow’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
1787 |  if ((opCode != TPM_FAMILY_CREATE) && (familyRow->flags & …
> tpm12: Initialize some variables for gcc ppc64el compiler

- src/tpm12/tpm_nvram.c
- src/tpm12/tpm_process.c
- src/tpm12/tpm_session.c
- src/tpm12/tpm_transport.c
- src/tpm2/Marshal.c
The -O3 passed to the ppc64el gcc-5 compiler on Ubuntu 16.04 causes
the following false positives:
gcc-5 -DHAVE_CONFIG_H -I. -I.. -include tpm_library_conf.h -I../include/libtpms -I../include/libtpms -fstack-protector-strong -DTPM_V12 -DTPM_PCCLIENT -DTPM_VOLATILE_LOAD -DTPM_ENABLE_ACTIVATE -DTPM_AES -DTPM_LIBTPMS_CALLBACKS -DTPM_NV_DISK -DTPM_POSIX -DTPM_NOMAINTENANCE_COMMANDS -g -O3 -fstack-protector-strong -DUSE_OPENSSL_FUNCTIONS_SYMMETRIC=1 -DUSE_OPENSSL_FUNCTIONS_EC=1 -DUSE_OPENSSL_FUNCTIONS_ECDSA=0 -DUSE_OPENSSL_FUNCTIONS_RSA=0 -Wall -Werror -Wreturn-type -Wsign-compare -Wno-self-assign -MT tpm12/libtpms_tpm12_la-tpm_session.lo -MD -MP -MF tpm12/.deps/libtpms_tpm12_la-tpm_session.Tpo -c tpm12/tpm_session.c -o tpm12/libtpms_tpm12_la-tpm_session.o
tpm12/tpm_session.c: In function …
> tpm12: Initialize some variables for gcc-5 ppc64el compiler

- debian/control
- debian/rules
We need to inform debhelper that it will be driving the action using autotools.
edit `debian/control` field `Build-Depends`: add `autotools-dev` and
`dh-autoreconf`
edit `debian/rules`:
* change the default target `%` to invoke `dh` with `autotools-dev` and
`autoreconf`
* remove from `override_dh_auto_configure` the invocation to `./autogen.sh`
obsoleted by `dh-autoreconf`
> make debhelper play nice with autotools

- .travis.yml
Run some additional IBM TSS2 related tests for better code
coverage. We need to switch to Bionic to get the tss2 package.
> Travis: Run additional IBM TSS2 related test; use Bionic

- tests/nvram_offsets.c
Add 2 more tests checking the size of arrays in the PERSISTENT_DATA
structure which expand with new commands.
> Tests: Add a check for arrays that expand with new commands

- src/tpm2/Marshal.c
- src/tpm2/Unmarshal.c
This patch comments unreference/dead code in Unmarshal.c/Marshal.c.
> tpm2: Comment dead code in Unmarshal.c/Marshal.c

- configure.ac
TPM 2 support has been in libtpms for quite some time now
and the experimental tag can be removed.
> build-sys: Remove 'experimental' tag from --with-tpm2

- src/tpm_tpm2_interface.c
This patch fixes two memory leaks in the new code in TPM2_GetInfo().
> tpm2: Fix memory leaks in TPM2_GetInfo()

- src/tpm2/crypto/openssl/CryptPrimeSieve.c
PrimeSieve was accessing the sieveMarks array at out-of-bounds index 5
due to a bug in other parts of the code. This patch fixes the issue
and prevents this access by limiting the values that 'next' can take on.
> tpm2: Prevent RSA 3072 related out-of-bounds access to sieveMarks[5]

- src/tpm2/NVDynamic.c
This PR addresses issue 133: https://github.com/stefanberger/libtpms/issues/133
bin/sh ../libtool  --tag=CC   --mode=compile x86_64-pc-linux-gnu-gcc \
-DHAVE_CONFIG_H -I. -I..    -include tpm_library_conf.h \
-I../include/libtpms -I../include/libtpms -fstack-protector-strong \
-D_POSIX_ -DTPM_POSIX -DTPM_LIBTPMS_CALLBACKS -I ./tpm2 \
-I ./tpm2/crypto -I ./tpm2/crypto/openssl -g -O2 \
-DUSE_OPENSSL_FUNCTIONS_SYMMETRIC=1 -DUSE_OPENSSL_FUNCTIONS_EC=1 \
-DUSE_OPENSSL_FUNCTIONS_ECDSA=1 -DUSE_OPENSSL_FUNCTIONS_RSA=1 \
-Wall -Werror -Wreturn-type -Wsign-compare -Wno-self-assign \
-c -o tpm2/libtpms_tpm2_la-NVDynamic.lo `test -f 'tpm2/NVDynamic.c' \
|| echo './'`tpm2/NVDynamic.c
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. \
-I.. -include tpm_library_conf.h -I../include/libtpms …
> tpm2: Fix a gcc 10.1.0 complaint

- src/tpm2/Unmarshal.c
- src/tpm2/crypto/CryptEccMain_fp.h
- src/tpm2/crypto/openssl/CryptEccMain.c
This PR fixes two issues with elliptic curves
- support for some elliptic curves is compiled in (via choice of #defines in TpmProfile.h) but missing OpenSSL support during runtime, so we have to filter the advertised capabilities to only show those curves that are supported
- Unmarshalling of certain elliptic curves was not supported
> Elliptic curve fixes

- src/tpm2/VendorString.h
> tpm2: Remove space after 'IBM' in MANUFACTURER

- CHANGES
- configure.ac
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
- include/libtpms/tpm_library.h
- src/tpm2/Unmarshal.c
- src/tpm2/VendorString.h
- src/tpm2/crypto/CryptEccMain_fp.h
- src/tpm2/crypto/openssl/CryptEccMain.c
This PR fixes two issues with elliptic curves
- support for some elliptic curves is compiled in (via choice of #defines in Implementation.h) but missing OpenSSL support during runtime, so we have to filter the advertised capabilities to only show those curves that are supported
- Unmarshalling of certain elliptic curves was not supported
The MANUFACTURER #define is changed from "IBM " to "IBM".
> Elliptic curve fixes, MANUFACTURER fix and update to 0.7.1

- CHANGES
- configure.ac
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
- include/libtpms/tpm_library.h
- src/tpm2/Unmarshal.c
- src/tpm2/VendorString.h
- src/tpm2/crypto/CryptEccMain_fp.h
- src/tpm2/crypto/openssl/CryptEccMain.c
This PR fixes two issues with elliptic curves
- support for some elliptic curves is compiled in (via choice of #defines in Implementation.h) but missing OpenSSL support during runtime, so we have to filter the advertised capabilities to only show those curves that are supported
- Unmarshalling of certain elliptic curves was not supported
The MANUFACTURER #define is changed from "IBM " to "IBM".
> Elliptic curve fixes, MANUFACTURER fix and update to 0.6.2

- src/tpm2/crypto/openssl/CryptRsa.c
For the RSA decryption we have to use an output buffer of the size of the
(largest possible) RSA key for the decryption to always work.
This fixes a stack corruption bug that caused a SIGBUS and termination of
'swtpm'.
> tpm2: Fix output buffer parameter and size for RSA decryption

- src/tpm2/crypto/openssl/CryptRsa.c
- src/tpm2/crypto/openssl/CryptSym.c
This series of patches fixes a few potential issues with symmetric decryption
- add check for CBC and ECB for input size being multiple of block size and return TPM_RC_SIZE in case it is not the case
- add missing EVP_CIPHER_CTX_set_padding(ctx,0) call that is needed for CBC end ECB decryption
- always use a temporary buffer for decryption; the size of this buffer meets the requirements for the EVP_DecryptUpdate() call. 
For RSA signing we set the PSS salt length to the digest length. Previously it was at the maximum possible length, but this is not how TPM 2 implements it.
> Fix a few issues with symmetric decryption and PSS salt

- src/tpm2/crypto/openssl/CryptRsa.c
In corner cases where the size of the salt and the size of the hash
to sign + 2 exceed the signature size we cannot use the salt length =
hash length but have to resort to using the maximum possible salt
length.
> tpm2: Restrict setting the PSS salt length to the digest length

- configure.ac
- src/tpm12/tpm_identity.c
- src/tpm2/Marshal_fp.h
- src/tpm2/NVMarshal.c
- src/tpm2/TpmFail.c
- src/tpm2/Unmarshal_fp.h
- src/tpm2/Utils.h
- src/tpm_library.c
- src/tpm_tpm12_interface.c
- src/tpm_tpm2_interface.c
Add -Wmissing-prototypes to CFLAGS and make functions static add #include
where necessary.
> [build-sys] Add -Wmissing-prototypes to CFLAGS and clean up

- configure.ac
- dist/libtpms.spec
- include/libtpms/tpm_library.h
- src/tpm2/PCR.c
- tests/tpm2_pcr_read.c
Fix PCRBelongsTCBGroup by adjusting the set of PCRs that belong to the TCB
Group. The effect of this is that PCR changes to PCR 16 (for example) do
not change the pcrUpdateCounter anymore. The effect *should not* have any
negative side effects when using the TPM.
We also need to update the test cases that now show a different
pcrUpdateCounter in the responses. Also 'swtpm' test cases need
to be fixed to expect the changed result.
> tpm2: fix PCRBelongsTCBGroup for PCClient (bugfix) 

- CHANGES
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
This PR prepares for libtpms 0.6.3 release.
> Prepare for libtpms 0.6.3 release

- CHANGES
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
This PR prepares for the libtpms 0.7.3 release.
> Prepare for libtpms 0.7.3 release

- src/tpm12/tpm_nvram.c
- src/tpm2/Marshal.c
This series of patches fixes compilation errors on s390x on Fedora 32.
> Fix s390x compilation errors on Fedora 32

- src/tpm2/TpmTypes.h
- src/tpm_tpm2_interface.c
The JSON returned by TPM2_GetInfo contains a leading zero in the level.
$> swtpm_ioctl --tcp :10000 --info 1
{"TPMSpecification":{"family":"2.0","level":00,"revision":162+0}}
This patch fixes this to:
$> swtpm_ioctl --tcp :10000 --info 1
{"TPMSpecification":{"family":"2.0","level":0,"revision":162+0}}
> tpm2: Fix the returned number in the JSON

- configure.ac
Use AC_LINK_IFELSE to check whether linker flags like 'now' and
'relro' are understood or remain unused (= useless), and only add them
to the set of HARDENING_LDFLAGS, if they are used by the linker. clang
for example does not seem to use them and Cygwin's linker does not
understand them.
Note: This patch merely improves on the handling of these flags but does
not solve a compilation issue when clang is used, unlike swtpm where
this created issues.
> build-sys: Use AC_LINK_IFELSE to check for understood linker flags

- src/Makefile.am
- src/tpm12/tpm_crypto.c
- src/tpm12/tpm_cryptoh.c
- src/tpm12/tpm_openssl_helpers.c
- src/tpm12/tpm_openssl_helpers.h
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm2/crypto/openssl/TpmToOsslMath.c
- src/tpm2/crypto/openssl/consttime.txt
This PR addresses possible constant time issues that may arise when passing secrets to certain OpenSSL BIGNUM operations.
> Address potential constant time issues

- debian/changelog
> debian: Fix typo in changelog

- src/tpm2/Session.c
cppcheck has detected the following issues in 2 functions. However,
neither one of the out-of-bounds array access can happen with the
existing code (see comments in patch).
src/tpm2/Session.c:399:5: note: After for loop, slotIndex has value 3
for(slotIndex = 0; slotIndex < MAX_LOADED_SESSIONS; slotIndex++)
^
src/tpm2/Session.c:414:15: note: Assuming condition is false
if(result != TPM_RC_SUCCESS)
^
src/tpm2/Session.c:419:15: note: Array index out of bounds
s_sessions[slotIndex].occupied = TRUE;
^
src/tpm2/Session.c:591:27: error: Array 's_sessions[3]' accessed at index 3, which is out of bounds. [arrayIndexOutOfBounds]
MemoryCopy(&s_sessions[slotIndex].session, session, sizeof(SESSION));
^
src/tpm2/Session.c:571:5: note: After for loop, slotIndex has value 3
for(slotIndex = 0; slotIndex < …
> tpm2: Address issues detected by cppcheck (false positives)

- .travis.yml
- Makefile.am
- configure.ac
Support setting different install paths for package config files
using the --with-pkgconfigdir option.
Signed-off-by: William Roberts <william.c.roberts@intel.com>
> configure: support --with-pkgconfigdir

- src/tpm2/NVMarshal.c
This patch addresses issue #177 by fixing some typos and error
reporting inconsistencies (how structures are spelled) in NVMarhsal.c.
> tpm2: Fix typos and error reporting inconsitencies in NVMarshal.c

- src/tpm2/crypto/openssl/CryptEccMain.c
This patch ensures that the leading zeros in the b parameter for NIST P521
are being kept so that HLK accepts the return parameters. Now 66 bytes are
reported for 'b' rather than only 65. Do the same for the 'a' parameter,
though that one was properly reported already because it didn't have any
leading zeros.
> tpm2: Return properly sized array for b parameter for NIST P521 (HLK)

- src/Makefile.am
- src/tpm2/BackwardsCompatibilityObject.c
- src/tpm2/BackwardsCompatibilityObject.h
- src/tpm2/ContextCommands.c
- src/tpm2/Context_spt.c
- src/tpm2/NVMarshal.c
- src/tpm2/NVMarshal.h
- src/tpm2/Object.c
- src/tpm2/Object_fp.h
- src/tpm2/crypto/openssl/CryptHash.c
This PR addresses issue #147 by switching to use ANY_OBJECT_Marshal to save key and hash contexts. Previously TPM_ContextSave was copying an OBJECT right out of memory into a buffer for export to the user. These buffers were much bigger than those produced by ANY_OBJECT_Marshal and are dependent on the object being exported. To be able to resume with OBJECTs written out on the old way by libtpms 0.7 some compatibility code is added to be able to load the old-style key contexts.
> Save key and hash contexts using ANY_OBJECT_Marshal

- src/tpm2/NVMarshal.c
- src/tpm2/crypto/openssl/CryptCmac.c
- src/tpm2/crypto/openssl/CryptRand.c
- src/tpm2/crypto/openssl/CryptSym.c
- src/tpm_tpm2_interface.c
Coverity seems to have gotten a bit more picky since its last run. Many of the detected issues are false positive. The double-free is very unlikely to occur since it happens only if an error branch is taken. See patch description.
> This PR addresses a few Coverity scan detected issues which are mostl false positives

- debian/control
> debian: Add missing pkg-config to debian/control

- src/tpm12/tpm_crypto.c
- src/tpm12/tpm_crypto_freebl.c
- src/tpm12/tpm_cryptoh.c
- src/tpm12/tpm_debug.c
- src/tpm12/tpm_debug.h
- src/tpm12/tpm_key.c
- src/tpm12/tpm_migration.c
- src/tpm12/tpm_nvram.c
- src/tpm12/tpm_storage.c
- src/tpm2/NVMarshal.c
This PR fixes a VM suspend issue when an externally loaded public key is loaded. It will otherwise put libtpms into failure mode since public keys were not handled correctly in ANY_OBJECT_Marshal.
> Fix VM suspend issue when externally loaded public key is loaded

- configure.ac
- src/tpm2/crypto/openssl/CryptSym.c
The TPM is supposed to provide the output IV in the ivInOut parameter in
CryptSymmetricEncrypt. In the case of using the openssl routines, the
output IV is missed, and the resulting output from the TPM is in the
input IV.
OpenSSL unfortunately does not export EVP_CIPHER_CTX_iv() until
tags/OpenSSL_1_1_0, so we have to fall back to the reference code for
previous OpenSSL versions.
Signed-off-by: William Roberts <william.c.roberts@intel.com>
> tpm2: CryptSym: fix AES output IV

- CHANGES
- configure.ac
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
- include/libtpms/tpm_library.h
- src/tpm2/crypto/openssl/CryptSym.c
- This PR fixes the AES output IV.
- Prepares for the 0.7.7 release.
> CryptSym: fix AES output IV and prepare for 0.7.7 release

- CHANGES
- configure.ac
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
- include/libtpms/tpm_library.h
- src/tpm2/crypto/openssl/CryptSym.c
- This PR fixes the AES output IV.
- Prepares for the 0.8.2 release.
> CryptSym: fix AES output IV and prepare for 0.8.2 release

- src/Makefile.am
- src/tpm2/crypto/openssl/ExpDCache.c
- src/tpm2/crypto/openssl/ExpDCache_fp.h
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm_tpm2_interface.c
Implement a cache for the private exponent 'D' and prime 'Q' so that we
do not have to recalculate 'Q' and 'D' every time an RSA key is used. For
a cache hit we now use ~34000 cycles and on a cache miss it needs around
130000 cycles. Previously it needed around 100000 cycles to calcuate 'Q'
and 'D'. Assuming that keys will be reused and the cache is big enough
for the number of keys being use (64 entries), it seems well worth it.
This solution is better than extending the OBJECT with 'D' since OBJECT is
kept in the TPM's NVRAM and we would then need more memory to store OBJECTs
there.
> tpm2: Implement a cache for the private exponent D and prime Q

- src/tpm2/NVMarshal.c
Do not call BLOCK_SKIP_READ once rc has been set to any error value.
Therefore, surround all occurrences of BLOCK_SKIP_READ() with tests
of 'rc'.
> tpm2: Surround all occurrences of BLOCK_SKIP_READ() with tests of 'rc'

- CHANGES
- src/tpm2/Global.h
- src/tpm2/Manufacture.c
- src/tpm2/NVMarshal.c
- src/tpm2/PropertyCap.c
- src/tpm2/Session.c
- src/tpm2/TpmProfile.h
This patch addresses issue #209.
The context gap for libtpms is currently only 0xff due to the CONTEXT_SLOT
being a UINT8. To extend this to 0xffff, we need to define the CONTEXT_SLOT
as UINT16 and introduce a global variable s_ContextArrayMask that takes on
two valid values, 0xff for simulating the CONTEXT_SLOT when it was UINT8
and 0xffff for usage with the new CONTEXT_SLOT of type UINT16. All
occurrences of casts to CONTEXT_SLOT are replaced with a macro
CONTEXT_SLOT_MASKED that applies this mask to a value instead of using the
cast. We also use it for some calculations to avoid spilling over from
1 byte into 2 bytes for example. The cast with the new code is the same as
applying the mask 0xffff, and using the 0xff mask we can simulate the old
CONTEXT_SLOT (1 byte), which we need for …
> tpm2: Switch to UINT16 for CONTEXT_SLOT and 64k context gap

- configure.ac
- src/Makefile.am
This allows user to set specific flags during compilation, without
overriding configure-time cflags necessary for compilation.
See also:
https://www.gnu.org/software/automake/manual/html_node/User-Variables.html
https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
> build-sys: leave CFLAGS/LDFLAGS for user to be defined

- .travis.yml
Since swtpm_setup has been rewritten in 'C' now we can drop a few
python dependencies but need libjson-glib-dev as a new dependency
for testing with swtpm's master branch.
> Travis: Install libjson-glib-dev and drop a few python dependencies

- CHANGES
- src/tpm2/Unmarshal.c
Windows 2019 Server padds the TPM_ContextLoad() command with additional
bytes up to TPM_PT_MAX_OBJECT_CONTEXT for the TPMS_CONTEXT part. Since
libtpms does not use an OBJECT to serialize the keys (anymore) it now
uses less bytes than the MAXimum of TPM_PT_MAX_OBJECT_CONTEXT bytes and
the padding leaves some unconsumed bytes that end up failing the command
since no left-over bytes are allowed in any command.
When unconsumed bytes are left in TPMS_CONTEXT_Unmarshal() we check that
the original passed in size was that of TPM_PT_MAX_OBJECT_CONTEXT and
only then consume the additional padding bytes. Luckily only one command
calls TPMS_CONTEXT_Unmarshal() so that no unwanted side effects should
occur anywhere else, such as no bytes left for unmarshalling the next
structure.
The wisdom behind …
> tpm2: Consume padding bytes in TPM2_ContextLoad() (Win2k19, issue #217)

- .travis.yml
- CHANGES
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
- src/tpm2/Unmarshal.c
This PR applies a work-around for a Windows 2016 and 2019 server bug and prepares for 0.8.3 release. Also adapt the Travis yaml to the recent changes to swtpm project that now has the json-glib dependency.
> Apply work-around for Windows 2016 and 2019 server bug and prepare for 0.8.3 release

- configure.ac
Run autoupdate and address the following issue:
configure.ac:10: warning: 'AM_CONFIG_HEADER': this macro is obsolete.
configure.ac:10: You should use the 'AC_CONFIG_HEADERS' macro instead.
> build-sys: Run autoupdate on configure.ac for autconf 2.71

- src/tpm2/Marshal.c
- src/tpm2/Marshal_fp.h
- src/tpm2/NVMarshal.c
- src/tpm2/Unmarshal.c
Reset buffer size indicators that are found to be too large so that we don't have bad buffer sizes in memory that can cause issues when marshaling the data upon saving volatile data for example.
Check for the maximum size of a buffer when marshaling data so we do not overstep the TPM2B's buffer size.
> Reset buffer size indicators that are too large and check for maximum size on marshalling

- src/tpm2/Unmarshal.c
Restore the original value of the memory location where data from
a stream was unmarshalled and the unmarshalled value was found to
be illegal.
> tpm2: Restore original values of unmarsalled value was illegal

- CHANGES
- configure.ac
- debian/changelog
- dist/libtpms.spec
- dist/libtpms.spec.in
- src/tpm2/Marshal.c
- src/tpm2/Marshal_fp.h
- src/tpm2/NVMarshal.c
- src/tpm2/Unmarshal.c
This PR backports patches that resolve issues with bad input values and set TPM2B buffer size indicators to '0' if the input value was larger than the actual TPM2B type's buffer and in other cases restore the original value of a field if the unmarshalled value was found to be illegal. This prevents keeping around illegal buffer sizes and illegal values in memory that may cause issues.
> Backport patches resolving issues with bad input values

- configure.ac
- dist/libtpms.spec
- include/libtpms/tpm_library.h
- src/tpm2/NVDynamic.c
Fix the following compiler warning from gcc 10.3.0 by using memcpy
instead of MemoryCopy (fixes issue #229).
tpm2/NVDynamic.c: In function 'NvRamGetEnd':
tpm2/NVDynamic.c:378:12: warning: function may return address of local variable [-Wreturn-local-addr]
378 |     return iter;
|            ^
tpm2/NVDynamic.c:339:26: note: declared here
339 |     NV_RAM_HEADER        header;
|                          ^
tpm2/NVDynamic.c: In function 'NvRamGetIndex':
tpm2/NVDynamic.c:411:12: warning: function may return address of local variable [-Wreturn-local-addr]
411 |     return currentAddr;
|            ^
tpm2/NVDynamic.c:339:26: note: declared here
339 |     NV_RAM_HEADER        header;
|                          ^
> tpm2: Avoid compiler warning by using memcpy instead of MemoryCopy (gcc 10.3)

- tests/fuzz.cc
This PR extends the fuzzer with state suspend/resume at every step.
> tests: Extend the fuzzer with state suspend/resume at every step

- src/tpm2/Unmarshal.c
Enable case statements depending on enabled key sizes of AES and Camellia.
> tpm2: Enable case statements depending on enabled key sizes of AES and Camellia

- src/tpm2/crypto/openssl/TpmToOsslMath.c
Use the EC_POINT_set/get_affine_coordinates function on OpenSSL >= 1.1.
These function are a 1:1 replacement for the
EC_POINT_set/get_affine_coordinates_GFp functions and are available
since OpenSSL 1.1 and are deprecated in OpenSSL 3.0.
This patch addresses one aspect of the OpenSSL 3.0 issues raised in
issue #215.
> tpm2: Use EC_POINT_set/get_affine_coordinates on OpenSSL >= 1.1

- src/tpm2/NVMarshal.c
Event sequence objects were never properly marshalled and when their state
was saved and later restored their state may have been corrupted. Fix this
now by also marshalling the state of event sequence objects.
Bump up the version of the HASH_OBJECT's header to '3' so that previously
written state can be resumed if an event sequence object is encountered
and we only unmarshal an event sequence object when the version is at least
'3'.
Fixes issue #259.
> tpm2: Marshal event sequence objects' hash state

- configure.ac
- src/tpm2/crypto/openssl/CryptRsa.c
- src/tpm2/crypto/openssl/Helpers.c
This PR fixes various aspects of the build of libtpms for OpenSSL 3.0 and also some runtime aspects of it.
> Fix build and runtime for OpenSSL 3.0

- src/tpm2/crypto/openssl/CryptCmac.c
- src/tpm2/crypto/openssl/CryptSym.c
- src/tpm_tpm2_interface.c
> tpm2: Report SM4 keysizes ing GetInfo's JSON if SM4 is enabled

- src/tpm2/Time.c
To avoid timeouts on short-running commands, such as TPM2_PCR_Extend,
avoid triggering the writing of the permanent state of the TPM 2
if only the clock was updated. So the clock by itself will not cause
the permanent state to be written out anymore but there have to be
other reasons as well.
The state will still be written out upon a TPM2_Shutdown, which is
supposed to be the last command to be sent to the TPM when shutting
down the VM/vTPM. Also, the permanent state will still carry the
latest clock value if it is retrieved via control channel for
VM/VTPM suspend.
The case that may be affected, but is of lesser importance, is the one
where swtpm's volatile state is written to storage using 'swtpm_ioctl -v'
and then swtpm is terminated and restarted (similar to suspend/resume)
and the …
> tpm2: Do not write permanent state if only clock changed

- src/tpm2/NVMarshal.c
If s_ContextSlotMask was not set since the TPM 2 was not initialized
by a call to TPM_Manufacture() or the state was not resumed, then
initialize the s_ContextSlotMask to 0xffff.
This situation can occur if a VM with an attached swtpm was started
and the VM's firmware either doesn't support TPM or didn't get to
initialize the vTPM.
The following commands recreated the issue with a SeaBIOS-only VM that
had no attached hard disk but an attached TPM 2:
virsh start BIOS-only-VM ; virsh save BIOS-only-VM save.bin ; \
virsh restore save.bin
Error: Failed to restore domain from save.bin
error: internal error: qemu unexpectedly closed the monitor: \
2022-01-04T19:26:18.835851Z qemu-system-x86_64: tpm-emulator: Setting the stateblob (type 2) failed with a TPM error 0x3 a parameter is bad …
> tpm2: When writing state initialize s_ContextSlotMask if not set

- src/tpm2/CompilerDependencies.h
Fix typo in the __GNUC_MINOR__ preprocessor symbol.
This change is unlikely to have any impact since it was used for
comparions for gcc version 4.2, which is not in use anymore by now.
Resolves: https://github.com/stefanberger/libtpms/issues/289
> tpm2: Fix typo in __GNUC_MINOR__ preprocessor symbol

- src/tpm2/NVMarshal.c
Address an issue discovered by Coverity and one issue where an potentially uninitialized variable was written to memory. Neither of the issues had any negative effects.
> Address a coverity issue and a variable access issue

- src/tpm2/crypto/openssl/CryptRsa.c
Openssl 3.0 did return an error if EVP_PKEY_CTX_set0_rsa_oaep_label was called
with label size 0. The function should only be called if the size of the label
is greater 0.
With this fix TPM2_RSA_Encrypt/Decrypt did work with OpenSSL 1.1 and 3.0
for encryption without label.
Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>
> tpm2: Do not call EVP_PKEY_CTX_set0_rsa_oaep_label() for label of size 0 (OSSL 3)

- configure.ac
- dist/libtpms.spec
- include/libtpms/tpm_library.h
- src/tpm2/crypto/openssl/CryptRsa.c
Openssl 3.0 did return an error if EVP_PKEY_CTX_set0_rsa_oaep_label was called
with label size 0. The function should only be called if the size of the label
is greater 0.
With this fix TPM2_RSA_Encrypt/Decrypt did work with OpenSSL 1.1 and 3.0
for encryption without label.
Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>
>  tpm2: Do not call EVP_PKEY_CTX_set0_rsa_oaep_label() for label of siz…  …e 0 (OSSL 3)

- configure.ac
Add probing for -fstack-protector to the existing
-fstack-protector-strong since not all platforms support either one
of them.
> build-sys: Add probing for -fstack-protector

- src/tpm12/tpm_nvram.c
- src/tpm2/Marshal.c
Hi,
while collecting some stable fixes for Ubuntu I found one patch that - AFAICS - wasn't upstreamed yet.
But I think these changes make sense to the project in general just as much.
Therefore I've prepared those for your consideration.
I kept Authorship info intact (= @vorlonofportland) but signed-off myself as I reworked them to match your commit styles.
P.S. I haven't found these as issues or open PRs nor in any recent branches. If I just missed them I beg your pardon and feel free to close.
> Fix a few uninitialized variables

- src/tpm2/crypto/openssl/Helpers.c
Check the return code of BN_div() when calculating Q and Qr of
a private key.
Resolves: https://github.com/stefanberger/libtpms/issues/304
> tpm2: Check return code of BN_div()

- src/tpm2/ExecCommand.c
Initialize a variable in ExecuteCommand following Coverity report
CID 1461252.
Down the callpath as reported in CID 1461252 in
TPMI_ST_COMMAND_TAG_Unmarshal() the passed-in value of
TPMI_ST_COMMAND_TAG *target is stored and possibly restored later on in
case of failure. Coverity complains that the variable is uninitialized.
While this is correct, there's no harm reading the uninitialized value
from the structure and possibly restoring it later on while not doing
anything else with it otherwise. Therefore, it's a false positive.
> tpm2: Initialize variable reported by Coverity (false positive)

- configure.ac
gcc 12.1 supports _FORTIFY_SOURCE=3. Modify the existing check for whether
_FORTIFY_SOURCE=2 can be used to test compile with the user provided
CFLAGS and only add _D_FORTIFY_SOURCE=2 to the HARDENING_CFLAGS if the
user doesn't provide anything that's not compatible.
Following an online article _FORTIFY_SOURCE=3 may add more overhead, so
we only go up to level 2 for now and let build servers or user provide
the higher level via the CFLAGS.
https://developers.redhat.com/blog/2021/04/16/broadening-compiler-checks-for-buffer-overflows-in-_fortify_source#what_s_next_for__fortify_source
> Fix configure script to support _FORTIFY_SOURCE=3

- src/tpm_debug.h
The build environment used by OSS-Fuzz reports this error.
```
In file included from /src/libtpms/src/tpm_debug.c:42:
/src/libtpms/src/tpm_debug.h:69:9: error: 'printf' macro redefined [-Werror,-Wmacro-redefined]
#define printf(...) TPMLIB_LogPrintf(__VA_ARGS__);
:         ^
/usr/include/x86_64-linux-gnu/bits/stdio2.h:110:11: note: previous definition is here
^
1 error generated.
```
The simple fix is to #undef printf in case it is #define'd.
> tpm: #undef printf in case it is #define'd (OSS-Fuzz)

- src/tpm_nvfile.c
In TPM_NVRAM_LoadData(), there is an unlikely path where the function
will return an error code but still expect the caller to free the
allocated data. At least some of the callers don't handle this correctly
so ensure that the caller only needs to free data if the function
returns success.
Reported by Coverity.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> nvfile: Free allocated memory on failure

- src/tpm2/CryptUtil.c
Check the secret size against the size of the buffer, not the size
member that has not been set yet.
Reported by Coverity.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> tpm2: Fix size check in CryptSecretDecrypt

- man/man3/TPMLIB_RegisterCallbacks.pod
- src/tpm2/BnMath.c
- src/tpm2/NVMarshal.c
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm_tpm2_interface.c
This PR resolves some TPM 2 code issue discovered by Coverity in agressive mode.
> Resolve some issue discovered by Coverity in agressive mode

- src/tpm2/crypto/openssl/Helpers.c
Do not set the RSA_FLAG_NO_BLINDING on RSA keys anymore. The BoringSSL
documentation states the following:
"RSA_FLAG_NO_BLINDING disables blinding of private operations, which is
a dangerous thing to do. It is deprecated and should not be used. It will
be ignored whenever possible."
So, follow this documentation. OpenSSL does not seem to say much about it.
Signed-off-by Stefan Berger <stefanb@linux.ibm.com>
> tpm2: Do not set RSA_FLAG_NO_BLINDING on RSA keys anymore

- src/tpm2/NVMarshal.c
> tpm2: Fix a typo in PERSISTENT_ALL_Unmarshal

- src/tpm12/tpm_crypto.c
Add support for building with libressl on non-bsd systems.
> libressl: add support

- tests/base64decode.c
- tests/common
- tests/freebl_sha1flattensize.c
- tests/tpm2_createprimary.c
- tests/tpm2_createprimary.sh
- tests/tpm2_pcr_read.c
- tests/tpm2_pcr_read.sh
- tests/tpm2_selftest.c
- tests/tpm2_selftest.sh
Set license identifier in test cases and fix output in case of file size error
> Set license identifier in test cases and fix output in case of file size error

- tests/Makefile.am
When building the tests with `make check` and slibtool the tests will then all fail to load `libtpms.so.0`.
```
$ ./base64decode
/tmp/libtpms/tests/.libs/base64decode: error while loading shared libraries: libtpms.so.0: cannot open shared object file: No such file or directory
```
This happens because they are linked with `-ltpms` rather than the `libtpms.la` file which has unexpected results with slibtool. GNU libtool does some magic to make this work while slibtool fails to link the dependency.
The correct way to link internal dependencies is directly with the libtool archive (`.la`) files where the `-lfoo` linker flags should be only used with external dependencies. Additionally `-no-undefined` is added to the LDFLAGS to ensure there aren't undefined references in the future.
Note:
* …
> tests: Fix the build with slibtool

- src/tpm2/crypto/openssl/CryptSym.c
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm2/crypto/openssl/Helpers_fp.h
Implement usage of OpenSSL 3 API for replacement of deprecated EVP_CIPHER_CTX_iv()
> Implement usage of OpenSSL 3 API for replacement of deprecated EVP_CIPHER_CTX_iv()

- src/tpm2/crypto/openssl/CryptSym.c
- src/tpm2/crypto/openssl/Helpers.c
- src/tpm2/crypto/openssl/Helpers_fp.h
Add a caching layer to GetEVPCipher() to avoid having to call evpfn() mulitple times. Instead, return the 'const EVP_CIPHER *' that a single call to evpfn() (for a particular algorithm + mode + key size) returned and cache it for subsequent calls.
> tpm2: Add a caching layer to GetEVPCipher() helper function

- src/tpm2/CryptUtil.c
Check that there are sufficient bytes in the buffer before reading the cipherSize from it. Also, reduce the bufferSize variable by the number of bytes that make up the cipherSize to avoid reading and writing bytes beyond the buffer in subsequent steps that do in-place decryption.
This fixes CVE-2023-1017 & CVE-2023-1018.
> tpm2: Check size of buffer before accessing it (CVE-2023-1017 & -1018)

- src/tpm2/EACommands.c
Fix the missing buffer size check that the TPM 2 errata v1.4 mentions in 2.6.2 by adding a buffer size check before reading 2 bytes from a TPM2B_NAME buffer. There's no known CVE for this.
> tpm2: Check size of TPM2B_NAME buffer before reading 2 bytes from it

- src/tpm12/tpm_crypto.c
This fixes the format specifiers in a printf statement. Detected by Coverity.
> tpm12: Use proper format specifier %zu for size_t (CID1517801 & 1517798)

- src/tpm_library.c
Address a false positive issue detect by Coverity (CID 1517797) about *buflen.
Per this assignment of buflen
cached_blobs[st].buflen = buffer ? buflen : BUFLEN_EMPTY_BUFFER;
the following is true:
If cached_blobs[].buffer is     NULL then *buflen  = BUFLEN_EMPTY_BUFFER
If cached_blobs[].buffer is not NULL then *buflen != BUFLEN_EMPTY_BUFFER
> Insert assert ensuring *buflen != BUFLEN_EMPTY_BUFFER (Coverity)

- src/tpm2/CommandCodeAttributes.c
Fix two locations where s_ccAttr[0].commandIndex is used to access the commandIndex, which does not work when bitfields are not used. Use GET_ATTRIBUTE() to access the field so that it works when bitfields are used and when they are not used. There are several locations in this file where GET_ATTRIBUTE() is already used to access commandIndex.
> tpm2: Use GET_ATTRIBUTE to get commandIndex from s_ccAttr

- src/tpm2/Object.c
This reverts commit e82727e546163817569aecb906f71ac955656e3f.
The issue has previously been resolved in commit 17255da54c.
> Revert "Object: clear out sensitive area if on load if not provided"

- src/tpm2/Object.c
- src/tpm2/Object_spt.c
- src/tpm2/crypto/CryptRsa.h
- src/tpm2/crypto/CryptRsa_fp.h
- src/tpm2/crypto/openssl/CryptRsa.c
- src/tpm2/crypto/openssl/Helpers.c
Upstream got rid of OBJECT's privateExponent and instead stores P,Q,dP,dQ, and qInv concatenated in a TPM2B in sensitive->sensitive.rsa.t. I don't want to get rid of OBJECT's privateExponent or pack the parameters like this, so therefore this series of patches sync's up the code with upstream as cautiously as possible while maintaining the OBJECT as it is.
> Sync with RSA changes from upstream

- src/tpm2/ContextCommands.c
Compute the RSA private key before saving an OBJECT as context.
> Compute RSA private key before saving an OBJECT as context

- tests/oss-fuzz.sh
The new TPM 2 code casts bigNum's to Crypt_Int, which has an array 'd' of type 'crypt_uword_t[2]' which then leads to the following types of errors that we haven't found another solution for so far.
Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-2675de6341d4e056d04ab49179b8e5b8bd456589
/src/libtpms/src/tpm2/crypto/openssl/CryptPrime.c:377:20: runtime error: index 23 out of bounds for type 'crypt_uword_t[2]' (aka 'unsigned long[2]')
#0 0x5b4196 in RsaAdjustPrimeCandidate_New libtpms/src/tpm2/crypto/openssl/CryptPrime.c:377:20
#1 0x5b4196 in RsaAdjustPrimeCandidate libtpms/src/tpm2/crypto/openssl/CryptPrime.c:405:9
#2 0x5b4366 in TpmRsa_GeneratePrimeForRSA libtpms/src/tpm2/crypto/openssl/CryptPrime.c:454:6
#3 0x590953 in CryptRsaGenerateKey …
> tests: oss-fuzz.sh: Append -fno-sanitize=bounds to CFLAGS

- src/tpm12/tpm_crypto.c
This fixes the build with LibreSSL 3.9.0 where many implicit declarations for `BN_`, `EVP_` and `RSA_` functions occur which were implicitly included before.
Also, `make check` passes for me with LibreSSL 3.9.0.
> tpm12: add missing openssl includes

- src/tpm2/VendorInfo.c
Restore the MANUFACTURER string "IBM" to what it was before commit 6dcb416ddf5c05b.
> tpm2: Remove trailing space in MANUFACTURER #define

- src/tpm2/EACommands.c
- src/tpm2/Global.h
- src/tpm2/Session.c
Replace the check for several session attributes flags with a call to IsCpHashUnionOccupied.
Note that the existing check for
session->u1.cpHash.b.size != 0 || session->attributes.isCpHashDefined
can be replaced with just session->attributes.isCpHashDefined since isCpHashDefined is always assigned '1' (SET) when session.u1.cpHash is given a value. isCpHashDefined is reset in SessionResetPolicyData() as part of resetting all attribute flags and cpHash size is set to 0.
> rev180: Introduce IsCpHashUnionOccupied and use it in simple case

- src/tpm12/tpm_crypto.c
Fedora Rawhide and CentOS 10 do not support OpenSSL engine anymore. Therefore, replace include of engine.h with err.h since the engine is not needed anyway but we only need the prototype of ERR_get_error_line_data.
> tpm12: Replace include of engine.h with err.h

- src/tpm2/EACommands.c
- src/tpm2/RuntimeCommands.c
Even though UINT16 when printed as hex number will only use up to 4 bytes and 3 more bytes for the prefix '0x' and terminating NUL (0xffff), extend the buffer to 16 bytes to address the following gcc issue:
tpm2/RuntimeCommands.c:450:44: error: ‘__builtin___snprintf_chk’ output
may be truncated before the last format character
[-Werror=format-truncation=]
snprintf(bufferhi, sizeof(bufferhi), "0x%x", commandCodeHi);
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note:
‘__builtin___snprintf_chk’ output between 4 and 11 bytes into a
destination of size 10
> tpm2: Extend buffer for printing a UINT16 into to 16 bytes (older gcc)

- src/tpm2/RuntimeAlgorithm.c
- src/tpm2/RuntimeProfile.c
Leave TPM_RC_FAILURE to severe cases that should never occur (regex cannot be compiled) and in other cases use TPM_RC_VALUE.
> RuntimeProfiles: Replace TPM_RC_FAILURE with TPM_RC_VALUE

- tests/tpm2_setprofile.c
Test that a user is able to choose a specific StateFormatLevel that is not required by any of the chosen commands but enables a bugfix in the TPM 2 code for example.
> tests: Add test case when user chooses specific StateFormatLevel

- src/tpm2/AlgorithmCap.c
- src/tpm2/RuntimeAlgorithm.c
- src/tpm2/crypto/openssl/CryptEccMain.c
Some PolicyCapability related function were missing filters for runtime-enabled curves and algorithms. Add them.
> Add missing filters to PolicyCapability related functions

- .travis.yml
Since swtpm now depends on libtpms >= 0.10 use swtpm's stable-0.9 branch for testing.
> Travis: Use swtpm's stable-0.9 branch for testing

- src/tpm2/NVMarshal.c
Add handling of the case of wanting to skip a block of code when no data are in the byte stream. This case has not occurred so far where a block of unmarshalling code needed to be skipped but also no data were there in the byte stream - it would have otherwise lead to errors while trying to unmarshal data that were not there. So far there was simply no code there that should have been skipped.
> tpm2: NVMarshal: Add missing case of skipping a block when none is there

- src/tpm2/RuntimeAlgorithm.c
- src/tpm2/RuntimeAlgorithm_fp.h
- src/tpm2/RuntimeProfile.c
- tests/object_size.c
- tests/tpm2_setprofile.c
- Add ecc-sm2-p256 to all profiles since it had been enabled for a long time
- When reconciling the enabled curves with the min. key size, disable those curves that can be disabled and don't have the min. required size
- Prevent the list of disabled algorithms to start with a comma
- Fix the display of disabled elliptic curve algorithms by considering the enabledEccCurves array
> Fix some issue with profiles

- src/tpm2/TpmMath_Util.c
- src/tpm2/TpmMath_Util_fp.h
- src/tpm2/crypto/CryptPrime_fp.h
- src/tpm2/crypto/openssl/CryptPrime.c
Add the new RSA key generation function from upstream but keep it disabled since it does not seem to add much value compared to the existing function. For backwards compatibility reasons related to keys derived from seeds this code can also not just replace the existing code since it is based on a new random number generation function that may produce slightly different random numbers.
> Add new RSA key generation function from upstream but keep it disabled

- src/tpm2/crypto/openssl/CryptRsa.c
When decryption fails then return TPM_RC_VALUE rather than TPM_RC_FAILURE. The old error code could indicate to an application or driver that something is wrong with the TPM (has possibly gone into failure mode) even though only the decryption failed, possibly due to a wrong key.
> tpm2: Return TPM_RC_VALUE upon decryption failure

- src/tpm2/crypto/CryptPrimeSieve_fp.h
- src/tpm2/crypto/openssl/CryptPrimeSieve.c
Add the missing entry to the sieveMarks array. The new entry would only be used for RSA 3072 keys but due to the following change in RsaAdjustPrimeLimit it will not be used.
primeLimit = s_LastPrimeInTable - 2;  // libtpms: Fix for 3072 bit keys to avoid mark=5
If it was to be used (above change removed) it would occasionally produce different RSA 3072 prime numbers from the TPM's seeds and therefore any change to the above will have to depend on the SEED_COMPAT_LEVEL so that the same keys are always produced.
Use the full sieveMarks array to generate RSA 3072 keys when SEED_COMPAT_LEVEL > SEED_COMPAT_LEVEL_RSA_PRIME_ADJUST_PREREV169, otherwise keep the previous adjustment to avoid mark=5.
> rev180: Add missing entry to sieveMarks array

- include/libtpms/tpm_library.h
- include/libtpms/tpm_library.h.in
- man/man3/Makefile.am
- man/man3/TPMLIB_WasManufactured.pod
- src/libtpms.syms
- src/tpm_library.c
- src/tpm_library_intern.h
- src/tpm_tpm12_interface.c
- src/tpm_tpm2_interface.c
Implement TPMLIB_WasManufactured API call for a TPM 2 so that callers can detect whether a TPM 2 instance was newly created and therefore the profile that was set was also applied.
> tpm2: Implement TPMLIB_WasManufactured API call

- tests/tpm2_setprofile.c
Use free rather than TPM_Free to avoid the following warning:
tpm2_setprofile.c:377:18: warning: passing 'char *' to parameter \
of type 'unsigned char *' converts between pointers to integer \
types with different sign [-Wpointer-sign]
TPM_Free(profile);
../include/libtpms/tpm_memory.h:57:36: note: passing argument to \
parameter 'buffer' here
void       TPM_Free(unsigned char *buffer);
> tests: Use free rather than TPM_Free (OS/X)

- src/tpm2/RuntimeProfile.c
When a non-modifyable profile is chosen then copy the StateFormatLevel (SFL) from the internal profile as before. A reason for copying the SFL is also because the user is not allowed to make modifications to this type of profile. Otherwise, if the user chooses a modifyable profile, then let the user choose the StateFormatLevel.
> tpm2: Adjust selection of StateFormatLevel

- src/tpm2/AlgorithmTests.c
- src/tpm2/NVCommands.c
- src/tpm2/Object_spt.c
- src/tpm2/TpmEcc_Signature_ECDSA.c
- src/tpm2/Unmarshal.c
- src/tpm2/crypto/openssl/CryptRsa.c
- src/tpm_library.c
- src/tpm_library_intern.h
- src/tpm_tpm2_interface.c
To avoid static analyzer warnings due to non-literal format strings being used, wrap asprintf in TPMLIB_asprintf and call vasprintf from there.
> tpm2: Wrap asprintf to avoid static analyzer warnings

- src/tpm2/CryptUtil.c
- src/tpm2/RuntimeAlgorithm.c
- tests/tpm2_setprofile.c
Allow setting the minimum HMAC key size and add enforcement gates.
> tpm2: Allow setting the minimum HMAC key size: min-hmac-key-size

- src/tpm2/RuntimeProfile.c
Restrict profile names to 32 characters to avoid having to carry excessively long names in the TPM's state file.
> tpm2: Restrict profile names to 32 characters

- man/man3/TPMLIB_SetProfile.pod
- src/tpm2/RuntimeAttributes.c
- src/tpm2/RuntimeProfile.c
- tests/tpm2_setprofile.c
If the user provided no attributes in the profile then never copy them from a modifiable profile assuming that the user wanted no attributes to be set. Also allow explicitly setting an empty string, which is possible since all attributes are optional.
> Allow user to provide an empty string as attributes and do not copy attributes from modifiable profile

- src/tpm2/RuntimeProfile.c
For any new commands, algorithms, and attributes a new profile 'default-v2' has to be started.
> tpm2: Freeze default-v1 profile

- src/tpm2/NVMarshal.c
Resolve an issue reported by Coverity caused by the maximum value of datasize (max. size of an NV index) that was allowed to be 0x10100 (17 bits) even though later on it tried to read an array of maximum size expressed by 16 bits (Coverity complaint). However, the maximum value of datasize could only ever have been MAX_NV_INDEX_SIZE, which is gated by restrictions on the size of an NV index. Therefore, restrict the maximum datasize of an NV index to MAX_NV_INDEX_SIZE (2048 bytes) since this is the maximum size that an NV index can be defined for.
> tpm2: Restrict NV index datasize to MAX_NV_INDEX_SIZE (CID 1608875)

- .github/workflows/ci.yml
Ubuntu 20.04 is EOL. Therefore, upgrade it to 22.04.
> ci: Update from ubuntu-20.04 to ubuntu-22.04 due to EOL

- src/tpm2/TpmProfile_Common.h
- tests/common
The simple changes make it compilable on GNU Hurd where it is currently failing to build.
Link: https://buildd.debian.org/status/package.php?p=libtpms&suite=sid
> tpm2 + test: Make it compilable on Debian GNU Hurd

- man/man3/TPMLIB_SetProfile.pod
- src/tpm2/RuntimeAlgorithm.c
- src/tpm2/RuntimeProfile.c
- src/tpm2/TpmProfile_Common.h
- tests/nvram_offsets.c
- tests/object_size.c
- tests/tpm2_setprofile.c
Currently, the defaults do not allow 4096-bit RSA keys, however many end users are starting to use them. The lack of support in libtpms - configured at compile time, not runtime - means that most Linux distros (which don't currently alter the defaults) do not allow the use of 4096-bit RSA keys inside virtual machines.
Not only does this prevent creating 4096-bit RSA keys in the tpm (e.g. tpm2_createprimary), but it also prevents loading external 4096-bit RSA keys into the VM's tpm, for example when attempting to use the tpm to verify an externally-generated data signature that was created using a 4096-bit RSA key (e.g. as part of a PolicyAuthorize and/or VerifySignature).
> Enable support for 4096-bit RSA keys by default

- src/tpm2/RuntimeProfile.c
Fix the following bugs in RuntimeProfileDedupStrItems:
- RuntimeProfileDedupStrItems did not memmove the correct number of bytes, leading to potential crashes.
- Also, it did not handle deduplicating the last item in the comma- separated list correctly.
> tpm2: Fix bugs in RuntimeProfileDedupStrItems

- src/tpm2/RuntimeProfile.c
RuntimeProfileDedupStrItems did not memmove the correct number of bytes, leading to potential crashes. Also, it did not handle deduplicating the last item in the comma-separated list.
> tpm2: Fix RuntimeProfileDedupStrItems

- src/tpm2/RuntimeProfile.c
- tests/tpm2_setprofile.c
To enable RSA-4096 in the default-v2 profile, set the stateFormatLevel to STATE_FORMAT_LEVEL_CURRENT (8).
> tpm2: Set SFL of default-v2 profile to STATE_FORMAT_LEVEL_CURRENT

- src/tpm2/SessionProcess.c
In CheckLockedOut replace the return code of TPM_RC_RETRY with TPM_RC_SUCCESS since it does not seem to be necessary to run the TPM2 command again but the TPM2 can continue executing the current command. If NVRAM wasn't available then the code in CheckLockedOut would return with an error already.
> tpm2: In CheckLockedOut replace TPM_RC_RETRY with TPM_RC_SUCCESS

- src/tpm2/crypto/openssl/BnToOsslMath.c
With LibreSSL 4.1.0 the `EC_POINTs_mul` function was removed, but the newer OpenSSL 3 code path works instead.
Running `make check` succeeds for me.
```
PASS: nvram_offsets
PASS: tpm2_cve-2023-1017.sh
PASS: tpm2_cve-2023-1018.sh
PASS: tpm2_pcr_read.sh
PASS: base64decode.sh
PASS: tpm2_setprofile.sh
PASS: object_size
PASS: tpm2_createprimary.sh
PASS: tpm2_selftest.sh
PASS: fuzz.sh
============================================================================
Testsuite summary for libtpms 0.11.0
============================================================================
============================================================================
```
> tpm2: fix build for LibreSSL 4.1.0

- .github/workflows/ci.yml
Backport the github actions script from the master branch. In the coveralls build, use the stable-0.9 branch of swtpm since later versions of swtpm need later versions of libtpms.
> ci: Add github actions script

- src/tpm2/TpmTypes.h
UBSAN complains about the following now:
runtime error: left shift of 129 by 24 places cannot be represented in type 'int'
Fix this (again) in the affected variables by casting the values to UINT32. Some of the fixes got lost in the recent re-base, others are new due to how the values are defined.
> tpm2: Add explicit casts to UINT32 to avoid UBSAN issue
